@startuml
skinparam monochrome true

Title State machine for an invoice

[*] --> Created
Created --> Pending : T1
Created --> Rejected : T2
Created --> Revoked : T3

Pending --> Deleted : T4
Pending --> Approved : T5
Pending --> Revoked : T6

Approved --> Approved : T7
Approved --> Pending : T8
Approved --> Deleted : T9

Revoked --> [*]
Deleted --> [*]
Rejected --> [*]

Approved : - Amount\n- Due
Rejected : - Problems

note bottom of Approved
    Final state.
    Not verifiable
end note

@enduml